#!/bin/bash
# check_beelzebub_tx_response_time

# set default thresholds. These will be overwritten if arguments are passed on the cli

# warning threshold
wval=2
# critical threshold
cval=5
# timeframe in sec
tval=5
# number of sessions to siege/benchmark
sval=5
# server address for siege to test transaction response time against
server="http://localhost:8080"

# siege location
siege="/usr/bin/siege"


return_nrpe(){ 
		return=$1
		shift 1
		message="$@"
		echo -e "$message"
		exit $return
}

parseOpts(){
options=':w:c:t:s:'

cflag=false
wflag=false
tflag=false
sflag=true
sval=3
while getopts $options opt; do
  case $opt in
    	w)
		wval=${OPTARG}
		wflag=true
		;;

	c)
                cval=${OPTARG}
		cflag=true
		;;
	
	t)
                tval=${OPTARG}
		tflag=true
		;;
	s)
                sval=${OPTARG}
		sflag=true
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		return_nrpe 2
		;;

	:  ) 
		echo "Missing option argument for -$OPTARG" >&2
		return_nrpe 2
		;;

	*  ) 
		echo "Unimplemented option: -$OPTARG" >&2
		return_nrpe 2
		;;
  esac
done

## Require flags, and numeric arguments for $OPTARG
if ! $wflag && ! [[ $wval =~ ^-?[0-9]+$ ]];
then
    echo "-w warning_threshold must be specified with integer argument" >&2
    return_nrpe 2
fi
if ! $cflag && ! [[ $cval =~ ^-?[0-9]+$ ]];
then
    echo "-c critical_threshold must be specified with integer argument" >&2
    return_nrpe 2
fi
if ! $tflag && ! [[ $tval =~ ^-?[0-9]+$ ]];
then
    echo "-t timeframe must be specified with argument in seconds" >&2
    return_nrpe 2
fi

}

runSiege(){
Gtag='\e[92m'
Ytag='\e[93m'
Rtag='\e[31m'
Dtag='\e[39m'

scmd="siege -q -c${sval} -t${tval}s -v ${server}"
# Check that our dependency, siege, is installed, and executable
 ${scmd} > /dev/null 2>&1 || {
	return_nrpe 2 "[CRITICAL] Could not run siege command ${scmd}"
	} && {
		resptime="$(${scmd} 2>&1 | grep "Response time" | awk '{print $3}')"
	} && {
		# Compare response time value to thresholds using expression floating point conditional operater
 		if expr ${resptime} '<=' ${wval} >/dev/null; then 
			return_nrpe 0 "${Gtag}[GREEN] Response Time (avg < ${wval}) | ${resptime}${Dtag}"
		elif expr ${resptime} '>=' ${wval} >/dev/null  && expr ${resptime} '<=' ${cval} >/dev/null ; then
			return_nrpe 1 "${Ytag}[WARNING]: Response Time (avg > ${wval}) | ${resptime}${Dtag}"
		elif expr ${resptime} '>=' ${cval} >/dev/null ; then
			return_nrpe 2 "${Rtag}[CRITICAL]: Response Time (avg > ${cval}) | ${resptime}${Dtag}"
		fi
	}
}


## If options passed, push them through to getopts, else use defaults
if [[ $# -gt 0 ]]; then
	parseOpts $@
else
	parseOpts -w ${wval} -c ${cval} -t ${tval} -s ${sval}
fi
runSiege

